name: 拉取Gitee代码-纯测试
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          repository: ZhiheZier_0719/online-shopping-system
          ref: dev